#!/bin/sh

umount /dev/sda1 || true
mkfs.ext4 -F -L nixos /dev/sda1
mount /dev/sda1 /mnt
nixos-generate-config --root /mnt

cp /ssh_pubkey /mnt/etc/nixos/terraform-nixos-public-key

cat /mnt/etc/nixos/configuration.nix | head -n $(($(cat /mnt/etc/nixos/configuration.nix | wc -l) - 1)) | grep -v grub > /mnt/etc/nixos/configuration.nix.next
echo "services.openssh.enable = true;" >> /mnt/etc/nixos/configuration.nix.next
echo "users.users.root.openssh.authorizedKeys.keyFiles = [ ./terraform-nixos-public-key ];" >> /mnt/etc/nixos/configuration.nix.next
echo "users.mutableUsers = false;" >> /mnt/etc/nixos/configuration.nix.next
echo "}" >> /mnt/etc/nixos/configuration.nix.next
mv /mnt/etc/nixos/configuration.nix.next /mnt/etc/nixos/configuration.nix

cat /mnt/etc/nixos/hardware-configuration.nix | head -n $(($(cat /mnt/etc/nixos/hardware-configuration.nix | wc -l) - 1)) > /mnt/etc/nixos/hardware-configuration.nix.next
echo "boot.loader.grub.enable = true;" >> /mnt/etc/nixos/hardware-configuration.nix.next
echo "boot.loader.grub.version = 2;" >> /mnt/etc/nixos/hardware-configuration.nix.next
echo "boot.loader.grub.device = \"/dev/sda\";" >> /mnt/etc/nixos/hardware-configuration.nix.next
echo "}" >> /mnt/etc/nixos/hardware-configuration.nix.next
mv /mnt/etc/nixos/hardware-configuration.nix.next /mnt/etc/nixos/hardware-configuration.nix

nixos-install
reboot
